services:
  postgres:
    image: postgres:17.9
    container_name: personal_budget_manager_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=personal_budget_manager_db
    ports:
      - 5432:5432

volumes:
  postgres_data: {}